In [2]:
import numpy as np
import qubogen

s = np.array([3,1,1,2,2,1])
q = qubogen.qubo_number_partition(s)
q

array([[-21,   3,   3,   6,   6,   3],
       [  3,  -9,   1,   2,   2,   1],
       [  3,   1,  -9,   2,   2,   1],
       [  6,   2,   2, -16,   4,   2],
       [  6,   2,   2,   4, -16,   2],
       [  3,   1,   1,   2,   2,  -9]])

In [3]:
from lava.lib.optimization.problems.problems import QUBO
from lava.lib.optimization.solvers.generic.solver import (
        SolverConfig,
        OptimizationSolver,
)

# Define QUBO problem
qubo = QUBO(q)

# Solve using generic OptimizationSolver
solver = OptimizationSolver(problem=qubo)
config = SolverConfig(timeout=3000, target_cost=-50) #, backend="Loihi2")
solution = solver.solve(config=config)

/home/iraitz/Documentos/Projects/Neuromorphic-Portfolio/.venv/lib/python3.10/site-packages/lava/utils/profiler.py:16: UserWarning: Loihi2HWProfiler could not be imported. Currently no profiler is available.
  warnings.warn("Loihi2HWProfiler could not be imported. "


In [12]:
s[solution.best_state.astype(bool)]

array([1, 1, 2, 1])

In [13]:
s[~solution.best_state.astype(bool)]

array([3, 2])